Milestone: Query and update animals table
Kashif-Saleem-Ghuman/vet-clinic-database pull request #3
Opened 2023-02-21 17:39 UTC by Kashif-Saleem-Ghuman

In this milestone 💪 

- [ ] Add new species column
- [ ] Add required data
- [ ] Make required queries
- [ ] Screenshots:

![01](https://user-images.githubusercontent.com/111677605/220419334-649ba339-1819-4259-b379-aa71778ffdba.JPG)
![animals_never_tried_to_escape](https://user-images.githubusercontent.com/111677605/220419378-12a3d04d-6b8b-47e9-9a9c-a56ffc94d572.JPG)
![avg_escape_attempts_as_per_birth_date_between_1990_2000](https://user-images.githubusercontent.com/111677605/220419386-af42d001-09f7-419e-a1ba-c9ec53a4e2bc.JPG)
![avg_weight](https://user-images.githubusercontent.com/111677605/220419393-365432bf-d7fb-467a-ba46-364c21726023.JPG)
![delete](https://user-images.githubusercontent.com/111677605/220419396-7016b012-d0c8-4239-877a-81867f790502.JPG)
![delete_rollback](https://user-images.githubusercontent.com/111677605/220419398-2a42d8e2-022f-499e-9e94-dfb399c8e6f0.JPG)
![digimon_pokemon](https://user-images.githubusercontent.com/111677605/220419402-ce15beba-2e22-4c9d-9037-f4005fa24d73.JPG)
![min_max_weight_type_animal](https://user-images.githubusercontent.com/111677605/220419405-0923124d-5eea-4ad0-a68e-4cefd9f3a994.JPG)
![most_escapes_nuetered_nonNuetered](https://user-images.githubusercontent.com/111677605/220419406-bbe86953-81f3-4183-ab9d-a098d59cbbd3.JPG)
![no_of_animals](https://user-images.githubusercontent.com/111677605/220419409-5e4c320b-65f0-4c0b-9061-862f4e757c1d.JPG)
![rollback](https://user-images.githubusercontent.com/111677605/220419410-4d3144d3-30cb-4813-9782-ab57c75635a8.JPG)
![unspecified](https://user-images.githubusercontent.com/111677605/220419414-9394b799-dd27-420c-8d21-44c49ae4bf92.JPG)

2023-02-21 18:34 UTC, hiromataba requested changes
Hi @Kashif-Saleem-Ghuman   :wave: :wave: 

![almost-there](https://user-images.githubusercontent.com/75126481/160092588-b3f37e8e-a1d9-4b14-84fc-7ec1fed7b3e5.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Your PR has a proper title and description  :+1: 
- Your linters are passing :heavy_check_mark:  
- Profesional README file :rocket: 

## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 18:34 UTC, hiromataba commented on data.sql
> +
- The weight of "Angemon" is `-45kg` not 45kg

![image](https://user-images.githubusercontent.com/75126481/220426457-13ba8323-8122-44d4-bc87-e7ea75be3d3d.png)

2023-02-21 18:34 UTC, hiromataba commented on data.sql
> +values ('Charmander', '2020-02-08', 0, False, 11);
- [ ] The weight of "Charmander" is -11kg not 11kg. 

![image](https://user-images.githubusercontent.com/75126481/220427863-288326ba-c18d-45fa-9004-679945341711.png)

2023-02-21 18:34 UTC, hiromataba commented on data.sql
> +values ('Plantmon', '2021-11-15', 2, True, 5.7);
- [ ] The weight of "Plantmon" is -5.7kg not 5.7kg.

![image](https://user-images.githubusercontent.com/75126481/220428688-1b256bca-dc72-456d-b9fe-22388668a513.png)

2023-02-22 07:05 UTC, 1GORDON approved these changes
# Status: APPROVED 🟢 

Hi @Kashif-Saleem-Ghuman ✋

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Highlights!
- Followed Gitflow ✔️
- Descriptive Pull request ✔️
- Professional readme ✔️

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-22 07:05 UTC, 1GORDON commented on queries.sql
> +-- correct wightt of Angemon
Great job @Kashif-Saleem-Ghuman 🤝

- [ ] [Optional] As stated by the previous reviewer, kindly add update the weight_kg value of `Squirtle` and add these changes to the data.sql file.

2023-02-22 07:37 UTC, merged